import { db } from './firebase-config.js';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, serverTimestamp, limit, query } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { $, $$, money, toast, openModal, closeModal, confirmDialog, emptyState, setPageTitle, escapeHtml } from './utils.js';
import { audit } from './data.js';
const schemas={customers:{title:'Pelanggan',fields:[['name','Nama','text'],['phone','Nomor HP','text'],['email','Email','email'],['address','Alamat','textarea']],extra:r=>`<td>${+r.points||0}</td><td>${money(r.totalSpent)}</td>`,heads:'<th>Poin</th><th>Total Belanja</th>'},suppliers:{title:'Supplier',fields:[['name','Nama Supplier','text'],['company','Perusahaan','text'],['phone','Nomor HP','text'],['whatsapp','WhatsApp','text'],['email','Email','email'],['address','Alamat','textarea'],['notes','Catatan','textarea']],extra:()=>'',heads:''}};
export async function renderContacts(container,type){const s=schemas[type];setPageTitle(s.title);container.innerHTML=`<div class="page-head"><div><h3>${s.title}</h3><p class="muted">Kelola data ${s.title.toLowerCase()}.</p></div><button id="addContact" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Tambah ${s.title}</button></div><div class="toolbar"><input id="contactSearch" class="grow" placeholder="Cari nama / HP / email"></div><div id="contactTable" class="card">Memuat...</div>`;$('#addContact').onclick=()=>form(type);$('#contactSearch').oninput=()=>load(type);await load(type)}
async function load(type){const s=schemas[type],snap=await getDocs(query(collection(db,type),limit(200)));let rows=snap.docs.map(d=>({id:d.id,...d.data()}));const term=$('#contactSearch')?.value.trim().toLowerCase();if(term)rows=rows.filter(r=>[r.name,r.phone,r.email,r.company].some(v=>String(v||'').toLowerCase().includes(term)));$('#contactTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Kontak</th>${s.heads}<th>Aksi</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${escapeHtml(r.name||'-')}</b>${r.company?`<br><small class="muted">${escapeHtml(r.company)}</small>`:''}</td><td>${escapeHtml(r.phone||r.whatsapp||'-')}<br><small>${escapeHtml(r.email||'')}</small></td>${s.extra(r)}<td><button class="btn btn-sm btn-ghost" data-edit="${r.id}">Edit</button> <button class="btn btn-sm btn-danger" data-del="${r.id}">Hapus</button></td></tr>`).join('')}</tbody></table></div>`:emptyState(`Belum ada ${s.title.toLowerCase()}`,`Tambahkan ${s.title.toLowerCase()} pertama Anda.`);$$('[data-edit]').forEach(b=>b.onclick=()=>form(type,rows.find(r=>r.id===b.dataset.edit)));$$('[data-del]').forEach(b=>b.onclick=()=>remove(type,rows.find(r=>r.id===b.dataset.del)))}
function form(type,row){const s=schemas[type];const fields=s.fields.map(([k,l,t])=>`<label class="field ${t==='textarea'?'full':''}">${l}${t==='textarea'?`<textarea name="${k}">${escapeHtml(row?.[k]||'')}</textarea>`:`<input name="${k}" type="${t}" ${k==='name'?'required':''} value="${escapeHtml(row?.[k]||'')}">`}</label>`).join('');const card=openModal(`<h3>${row?'Edit':'Tambah'} ${s.title}</h3><form id="contactForm"><div class="form-grid">${fields}</div><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Batal</button><button class="btn btn-primary">Simpan</button></div></form>`);card.querySelector('#contactForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={};s.fields.forEach(([k])=>data[k]=String(fd.get(k)||'').trim());data.updatedAt=serverTimestamp();if(row)await updateDoc(doc(db,type,row.id),data);else await addDoc(collection(db,type),{...data,...(type==='customers'?{points:0,totalTransactions:0,totalSpent:0}:{}),createdAt:serverTimestamp()});await audit(`${row?'edit':'tambah'} ${s.title.toLowerCase()}`,data.name);toast(`${s.title} disimpan`);closeModal();load(type)}}
async function remove(type,row){const s=schemas[type];if(!await confirmDialog(`Hapus ${s.title.toLowerCase()}?`,`${row.name} akan dihapus.`))return;await deleteDoc(doc(db,type,row.id));await audit(`hapus ${s.title.toLowerCase()}`,row.name);toast(`${s.title} dihapus`);load(type)}
