import { db } from './firebase-config.js';
import { currentProfile, isAdmin } from './auth.js';
import { collection, getDocs, query, where, Timestamp, orderBy, limit } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { money, setPageTitle, emptyState, dateTime, statusBadge } from './utils.js';
let chart;
export async function renderDashboard(container){setPageTitle('Dashboard');container.innerHTML=`<div class="grid grid-4" id="dashStats"><div class="card">Memuat statistik...</div></div><div class="grid grid-2" style="margin-top:16px"><div class="card"><div class="page-head"><h3>Grafik Penjualan</h3><select id="chartPeriod"><option value="daily">7 Hari</option><option value="monthly">6 Bulan</option></select></div><canvas id="salesChart" height="125"></canvas></div><div class="card"><h3>Produk Terlaris</h3><div id="bestSellers">Memuat...</div></div></div><div class="card" style="margin-top:16px"><h3>Transaksi Terbaru</h3><div id="recentSales">Memuat...</div></div>`;await loadStats();await renderChart('daily');document.querySelector('#chartPeriod').addEventListener('change',e=>renderChart(e.target.value));await loadRecent()}
async function getSalesSince(date){if(isAdmin())return getDocs(query(collection(db,'sales'),where('createdAt','>=',Timestamp.fromDate(date))));const own=await getDocs(query(collection(db,'sales'),where('cashierId','==',currentProfile.uid)));return {docs:own.docs.filter(d=>(d.data().createdAt?.toDate?.()||new Date(0))>=date),forEach(fn){this.docs.forEach(fn)},get size(){return this.docs.length}}}
async function loadStats(){const now=new Date(),today=new Date(now);today.setHours(0,0,0,0);const month=new Date(now.getFullYear(),now.getMonth(),1);const [todaySales,monthSales,products,customers]=await Promise.all([getSalesSince(today),getSalesSince(month),getDocs(collection(db,'products')),getDocs(collection(db,'customers'))]);let todayRevenue=0,todayProfit=0,monthRevenue=0,monthProfit=0;todaySales.forEach(d=>{const s=d.data();if(s.status!=='cancelled'){todayRevenue+=+s.total||0;todayProfit+=+s.profit||0}});monthSales.forEach(d=>{const s=d.data();if(s.status!=='cancelled'){monthRevenue+=+s.total||0;monthProfit+=+s.profit||0}});let low=0,out=0;products.forEach(d=>{const p=d.data(),st=+p.stock||0,min=+p.minStock||0;if(st<=0)out++;else if(st<=min)low++});const cards=[['Penjualan Hari Ini',money(todayRevenue),'money-bill-trend-up'],['Transaksi Hari Ini',todaySales.size,'receipt'],['Keuntungan Hari Ini',money(todayProfit),'chart-line'],['Jumlah Produk',products.size,'boxes-stacked'],['Hampir Habis',low,'triangle-exclamation'],['Produk Habis',out,'box-open'],['Total Pelanggan',customers.size,'users'],['Penjualan Bulan Ini',money(monthRevenue),'calendar-check']];document.querySelector('#dashStats').innerHTML=cards.map(c=>`<div class="card stat-card"><div><div class="label">${c[0]}</div><div class="value">${c[1]}</div></div><div class="stat-icon"><i class="fa-solid fa-${c[2]}"></i></div></div>`).join('')}
async function renderChart(period){const d=new Date();d.setDate(d.getDate()-(period==='daily'?6:180));const snap=await getSalesSince(d);const map=new Map();if(period==='daily'){for(let i=6;i>=0;i--){const x=new Date();x.setDate(x.getDate()-i);map.set(x.toISOString().slice(0,10),0)}}else{for(let i=5;i>=0;i--){const x=new Date();x.setMonth(x.getMonth()-i);map.set(`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`,0)}}snap.forEach(doc=>{const s=doc.data();if(s.status==='cancelled')return;const x=s.createdAt?.toDate?.();if(!x)return;const k=period==='daily'?x.toISOString().slice(0,10):`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`;if(map.has(k))map.set(k,map.get(k)+(+s.total||0))});const ctx=document.querySelector('#salesChart');if(chart)chart.destroy();chart=new Chart(ctx,{type:'line',data:{labels:[...map.keys()],datasets:[{label:'Omzet',data:[...map.values()],tension:.3,fill:false}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>'Rp'+Number(v).toLocaleString('id-ID')}}}}}) ; await loadBestSellers(snap)}
async function loadBestSellers(salesSnap){const m=new Map();salesSnap.forEach(d=>{const s=d.data();if(s.status==='cancelled')return;(s.items||[]).forEach(i=>{const a=m.get(i.productId)||{name:i.name,qty:0,revenue:0};a.qty+=+i.qty||0;a.revenue+=+i.subtotal||0;m.set(i.productId,a)})});const rows=[...m.values()].sort((a,b)=>b.qty-a.qty).slice(0,5);document.querySelector('#bestSellers').innerHTML=rows.length?rows.map((r,i)=>`<div class="receipt-row" style="padding:9px 0;border-bottom:1px solid var(--line)"><span><b>#${i+1}</b> ${r.name}<br><small class="muted">${r.qty} terjual</small></span><b>${money(r.revenue)}</b></div>`).join(''):emptyState('Belum ada penjualan','Produk terlaris akan muncul setelah transaksi.')}
async function loadRecent(){let snap;try{snap=isAdmin()?await getDocs(query(collection(db,'sales'),orderBy('createdAt','desc'),limit(8))):await getDocs(query(collection(db,'sales'),where('cashierId','==',currentProfile.uid)))}catch{snap=isAdmin()?await getDocs(collection(db,'sales')):await getDocs(query(collection(db,'sales'),where('cashierId','==',currentProfile.uid)))}const rows=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,8);document.querySelector('#recentSales').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>No Transaksi</th><th>Waktu</th><th>Kasir</th><th>Total</th><th>Pembayaran</th><th>Status</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${s.number||s.id}</td><td>${dateTime(s.createdAt)}</td><td>${s.cashierName||'-'}</td><td>${money(s.total)}</td><td>${s.paymentMethod||'-'}</td><td>${statusBadge(s.status||'completed')}</td></tr>`).join('')}</tbody></table></div>`:emptyState('Belum ada transaksi','Transaksi terbaru akan muncul di sini.')}
