import { db } from './firebase-config.js';
import { currentProfile } from './auth.js';
import { collection, getDocs, doc, runTransaction, serverTimestamp, addDoc, query, orderBy, limit } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { $, $$, toast, openModal, closeModal, setPageTitle, statusBadge, dateTime, escapeHtml, num, emptyState } from './utils.js';
import { audit } from './data.js';
let products=[];
export async function renderInventory(container){setPageTitle('Stok');container.innerHTML=`<div class="page-head"><div><h3>Manajemen Stok</h3><p class="muted">Stok masuk, penyesuaian, dan riwayat pergerakan stok.</p></div><div class="actions"><button id="stockInBtn" class="btn btn-success">Stok Masuk</button><button id="adjustBtn" class="btn btn-primary">Penyesuaian</button></div></div><div id="stockTable" class="card">Memuat...</div><div class="card" style="margin-top:16px"><h3>Riwayat Stok Terbaru</h3><div id="stockHistory">Memuat...</div></div>`;$('#stockInBtn').onclick=()=>stockForm('in');$('#adjustBtn').onclick=()=>stockForm('adjust');await Promise.all([loadStock(),loadHistory()])}
async function loadStock(){const s=await getDocs(collection(db,'products'));products=s.docs.map(d=>({id:d.id,...d.data()}));$('#stockTable').innerHTML=products.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Produk</th><th>Stok</th><th>Minimum</th><th>Status</th></tr></thead><tbody>${products.map(p=>{const st=+p.stock||0,min=+p.minStock||0,status=st<=0?'Habis':st<=min?'Hampir habis':'Aman';return `<tr><td><b>${escapeHtml(p.name)}</b></td><td>${st} ${escapeHtml(p.unit||'pcs')}</td><td>${min}</td><td>${statusBadge(status)}</td></tr>`}).join('')}</tbody></table></div>`:emptyState('Belum ada produk','Tambah produk terlebih dahulu.')}
async function loadHistory(){let s;try{s=await getDocs(query(collection(db,'stockMovements'),orderBy('createdAt','desc'),limit(30)))}catch{s=await getDocs(collection(db,'stockMovements'))}const rows=s.docs.map(d=>d.data()).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,30);$('#stockHistory').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Produk</th><th>Jenis</th><th>Jumlah</th><th>Sebelum → Sesudah</th><th>Pengguna</th><th>Catatan</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateTime(r.createdAt)}</td><td>${escapeHtml(r.productName||'-')}</td><td>${escapeHtml(r.type||'-')}</td><td>${r.quantity>0?'+':''}${r.quantity}</td><td>${r.before} → ${r.after}</td><td>${escapeHtml(r.userName||'-')}</td><td>${escapeHtml(r.note||'')}</td></tr>`).join('')}</tbody></table></div>`:emptyState('Belum ada riwayat','Perubahan stok akan dicatat di sini.')}
function stockForm(mode){if(!products.length)return toast('Belum ada produk.','warning');const card=openModal(`<h3>${mode==='in'?'Stok Masuk':'Penyesuaian Stok'}</h3><form id="stockForm"><div class="form-grid"><label class="field full">Produk<select name="productId" required>${products.map(p=>`<option value="${p.id}">${escapeHtml(p.name)} — stok ${+p.stock||0}</option>`).join('')}</select></label>${mode==='adjust'?`<label class="field">Arah<select name="direction"><option value="plus">Tambah</option><option value="minus">Kurangi</option></select></label>`:''}<label class="field">Jumlah<input name="quantity" type="number" min="1" required value="1"></label><label class="field full">Keterangan / alasan<textarea name="note" required></textarea></label></div><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Batal</button><button class="btn btn-primary">Simpan</button></div></form>`);card.querySelector('#stockForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),id=fd.get('productId'),qty=num(fd.get('quantity')),delta=mode==='adjust'&&fd.get('direction')==='minus'?-qty:qty,note=String(fd.get('note')||'').trim();if(qty<=0)return toast('Jumlah harus lebih dari 0.','warning');try{await runTransaction(db,async tx=>{const ref=doc(db,'products',id),snap=await tx.get(ref);if(!snap.exists())throw new Error('Produk tidak ditemukan');const p=snap.data(),before=+p.stock||0,after=before+delta;if(after<0)throw new Error('Stok tidak boleh negatif');tx.update(ref,{stock:after,updatedAt:serverTimestamp()});const m=doc(collection(db,'stockMovements'));tx.set(m,{productId:id,productName:p.name,type:mode==='in'?'stock_in':'adjustment',quantity:delta,before,after,userId:currentProfile.uid,userName:currentProfile.name||currentProfile.email,note,createdAt:serverTimestamp()})});await audit(mode==='in'?'stok masuk':'penyesuaian stok',`${id}: ${delta}`);toast('Stok berhasil diperbarui');closeModal();await Promise.all([loadStock(),loadHistory()])}catch(err){toast(err.message,'error')}}}
