import { db } from './firebase-config.js';
import { currentProfile } from './auth.js';
import { collection, getDocs, doc, runTransaction, serverTimestamp, query, orderBy, limit } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { $, $$, money, num, toast, openModal, closeModal, setPageTitle, dateTime, escapeHtml, emptyState } from './utils.js';
import { audit } from './data.js';
let suppliers=[],products=[];
export async function renderPurchases(container){setPageTitle('Pembelian / Restock');container.innerHTML=`<div class="page-head"><div><h3>Pembelian Barang</h3><p class="muted">Catat pembelian supplier dan tambah stok otomatis.</p></div><button id="addPurchase" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Pembelian Baru</button></div><div id="purchaseTable" class="card">Memuat...</div>`;$('#addPurchase').onclick=purchaseForm;await Promise.all([loadMasters(),loadPurchases()])}
async function loadMasters(){const [s,p]=await Promise.all([getDocs(collection(db,'suppliers')),getDocs(collection(db,'products'))]);suppliers=s.docs.map(d=>({id:d.id,...d.data()}));products=p.docs.map(d=>({id:d.id,...d.data()}))}
async function loadPurchases(){let s;try{s=await getDocs(query(collection(db,'purchases'),orderBy('createdAt','desc'),limit(50)))}catch{s=await getDocs(collection(db,'purchases'))}const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));$('#purchaseTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Nomor</th><th>Tanggal</th><th>Supplier</th><th>Produk</th><th>Total</th><th>Pengguna</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.number||r.id)}</td><td>${dateTime(r.createdAt)}</td><td>${escapeHtml(r.supplierName||'-')}</td><td>${(r.items||[]).length} item</td><td>${money(r.total)}</td><td>${escapeHtml(r.userName||'-')}</td></tr>`).join('')}</tbody></table></div>`:emptyState('Belum ada pembelian','Catat restock pertama Anda.')}
function purchaseForm(){if(!products.length)return toast('Tambahkan produk terlebih dahulu.','warning');const card=openModal(`<h3>Pembelian Baru</h3><form id="purchaseForm"><div class="form-grid"><label class="field full">Supplier<select name="supplierId"><option value="">Tanpa supplier</option>${suppliers.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('')}</select></label><label class="field full">Produk<select name="productId">${products.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('')}</select></label><label class="field">Quantity<input name="qty" type="number" min="1" value="1" required></label><label class="field">Harga Beli / unit<input name="cost" type="number" min="0" required></label><label class="field full">Catatan<textarea name="note"></textarea></label></div><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Batal</button><button class="btn btn-primary">Simpan Pembelian</button></div></form>`);const pSel=card.querySelector('[name=productId]'),cost=card.querySelector('[name=cost]');const sync=()=>cost.value=+products.find(p=>p.id===pSel.value)?.costPrice||0;pSel.onchange=sync;sync();card.querySelector('#purchaseForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),pid=fd.get('productId'),qty=num(fd.get('qty')),unitCost=num(fd.get('cost')),supplier=suppliers.find(s=>s.id===fd.get('supplierId'));if(qty<=0)return toast('Quantity tidak valid.','warning');const number=`PO-${Date.now()}`,purchaseRef=doc(collection(db,'purchases'));try{await runTransaction(db,async tx=>{const pref=doc(db,'products',pid),ps=await tx.get(pref);if(!ps.exists())throw new Error('Produk tidak ditemukan');const p=ps.data(),before=+p.stock||0,after=before+qty;tx.update(pref,{stock:after,costPrice:unitCost,updatedAt:serverTimestamp()});tx.set(purchaseRef,{number,supplierId:supplier?.id||null,supplierName:supplier?.name||'Tanpa supplier',items:[{productId:pid,name:p.name,qty,costPrice:unitCost,subtotal:qty*unitCost}],total:qty*unitCost,userId:currentProfile.uid,userName:currentProfile.name||currentProfile.email,note:String(fd.get('note')||''),createdAt:serverTimestamp()});tx.set(doc(collection(db,'stockMovements')),{productId:pid,productName:p.name,type:'purchase',quantity:qty,before,after,userId:currentProfile.uid,userName:currentProfile.name||currentProfile.email,note:number,createdAt:serverTimestamp()})});await audit('pembelian',number);toast('Pembelian tersimpan dan stok bertambah');closeModal();await Promise.all([loadMasters(),loadPurchases()])}catch(err){toast(err.message,'error')}}}
