import { openModal, closeModal, toast } from './utils.js';
let stream=null,reader=null,deviceIds=[],deviceIndex=0,lastCode='',lastAt=0;
async function stop(){try{reader?.reset?.()}catch{}reader=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
export async function openScanner(onDetected){
  if(!navigator.mediaDevices?.getUserMedia){toast('getUserMedia tidak tersedia. Gunakan HTTPS dan browser modern.','error',6000);return}
  const card=openModal(`<h3><i class="fa-solid fa-barcode"></i> Scan Barcode</h3><p class="muted">Arahkan barcode ke dalam kotak.</p><div class="scanner-wrap"><video id="scannerVideo" autoplay muted playsinline></video><div class="scan-box"></div><div class="scan-line"></div></div><div class="scanner-controls"><button id="flashBtn" class="btn btn-ghost"><i class="fa-solid fa-bolt"></i> Flash</button><button id="switchCameraBtn" class="btn btn-ghost"><i class="fa-solid fa-camera-rotate"></i> Ganti Kamera</button></div><p id="scannerInfo" class="tiny muted" style="text-align:center">Meminta izin kamera...</p>`,{size:'modal-lg'});
  const originalClose=closeModal;card.parentElement.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))stop()});card.querySelector('[data-close-modal]').addEventListener('click',stop,{once:true});
  async function start(deviceId){await stop();try{stream=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:'environment'}},audio:false});const v=card.querySelector('#scannerVideo');v.srcObject=stream;await v.play();const devices=await navigator.mediaDevices.enumerateDevices();deviceIds=devices.filter(d=>d.kind==='videoinput').map(d=>d.deviceId);const track=stream.getVideoTracks()[0];const caps=track.getCapabilities?.()||{};card.querySelector('#flashBtn').disabled=!caps.torch;card.querySelector('#flashBtn').onclick=async()=>{try{await track.applyConstraints({advanced:[{torch:true}]});setTimeout(()=>track.applyConstraints({advanced:[{torch:false}]}).catch(()=>{}),1500)}catch{toast('Flash tidak didukung perangkat ini.','warning')}};card.querySelector('#scannerInfo').textContent='Scanner aktif — kamera: '+(track.label||'kamera');if(window.ZXing){reader=new ZXing.BrowserMultiFormatReader();reader.decodeFromVideoElementContinuously(v,(result,err)=>{if(!result)return;const code=result.getText();const now=Date.now();if(code===lastCode&&now-lastAt<2200)return;lastCode=code;lastAt=now;beep();stop();originalClose();onDetected(code)})}else{card.querySelector('#scannerInfo').textContent='Library ZXing gagal dimuat.'}}catch(e){console.error(e);toast(`Kamera gagal: ${e.name||e.message}`,'error',6000);card.querySelector('#scannerInfo').textContent='Tidak dapat mengakses kamera. Pastikan izin kamera aktif dan situs menggunakan HTTPS.'}}
  }
  card.querySelector('#switchCameraBtn').onclick=()=>{if(deviceIds.length<2)return toast('Hanya satu kamera terdeteksi.','warning');deviceIndex=(deviceIndex+1)%deviceIds.length;start(deviceIds[deviceIndex])};await start();
}
function beep(){try{const a=new AudioContext();const o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=880;g.gain.value=.06;o.start();o.stop(a.currentTime+.09)}catch{}}
export function stopScanner(){return stop()}
