import { db } from './firebase-config.js';
import { currentProfile } from './auth.js';
import { collection, getDocs, addDoc, updateDoc, doc, serverTimestamp, Timestamp, query, where } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { $, money, num, toast, openModal, closeModal, setPageTitle, dateTime, emptyState, escapeHtml } from './utils.js';
import { audit } from './data.js';
let openShift=null;
export async function renderShifts(container){setPageTitle('Shift Kasir');container.innerHTML=`<div class="page-head"><div><h3>Shift Kasir</h3><p class="muted">Catat modal awal, penjualan, uang aktual, dan selisih kas.</p></div><div id="shiftAction"></div></div><div id="shiftCurrent"></div><div class="card" style="margin-top:16px"><h3>Riwayat Shift</h3><div id="shiftHistory">Memuat...</div></div>`;await load()}
async function load(){const s=await getDocs(query(collection(db,'shifts'),where('cashierId','==',currentProfile.uid)));const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.openedAt?.seconds||0)-(a.openedAt?.seconds||0));openShift=rows.find(r=>r.status==='open')||null;$('#shiftAction').innerHTML=openShift?`<button id="closeShift" class="btn btn-danger">Tutup Shift</button>`:`<button id="openShift" class="btn btn-success">Buka Shift</button>`;if(openShift)$('#closeShift').onclick=closeForm;else $('#openShift').onclick=openForm;$('#shiftCurrent').innerHTML=openShift?`<div class="grid grid-3"><div class="card stat-card"><div><div class="label">Modal Awal</div><div class="value">${money(openShift.openingCash)}</div></div></div><div class="card stat-card"><div><div class="label">Dibuka</div><div class="value" style="font-size:1rem">${dateTime(openShift.openedAt)}</div></div></div><div class="card stat-card"><div><div class="label">Status</div><div class="value" style="font-size:1rem">OPEN</div></div></div></div>`:`<div class="card">${emptyState('Belum ada shift aktif','Buka shift sebelum mulai kasir.')}</div>`;$('#shiftHistory').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Dibuka</th><th>Ditutup</th><th>Modal</th><th>Tunai</th><th>Non-tunai</th><th>Aktual</th><th>Selisih</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateTime(r.openedAt)}</td><td>${r.closedAt?dateTime(r.closedAt):'-'}</td><td>${money(r.openingCash)}</td><td>${money(r.cashSales)}</td><td>${money(r.nonCashSales)}</td><td>${money(r.actualCash)}</td><td>${money(r.difference)}</td><td>${escapeHtml(r.status)}</td></tr>`).join('')}</tbody></table></div>`:emptyState('Belum ada riwayat','Riwayat shift akan muncul setelah dibuka.')}
function openForm(){const c=openModal(`<h3>Buka Shift</h3><form id="openShiftForm"><label class="field">Modal awal kas<input name="cash" type="number" min="0" required value="0"></label><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Batal</button><button class="btn btn-success">Buka Shift</button></div></form>`,{size:'modal-sm'});c.querySelector('#openShiftForm').onsubmit=async e=>{e.preventDefault();const cash=num(new FormData(e.currentTarget).get('cash'));await addDoc(collection(db,'shifts'),{cashierId:currentProfile.uid,cashierName:currentProfile.name||currentProfile.email,openingCash:cash,status:'open',openedAt:serverTimestamp()});await audit('buka shift',`Modal ${cash}`);toast('Shift dibuka');closeModal();load()}}
async function closeForm(){const since=openShift.openedAt?.toDate?.()||new Date();const s=await getDocs(query(collection(db,'sales'),where('createdAt','>=',Timestamp.fromDate(since))));let cash=0,non=0,count=0;s.forEach(d=>{const x=d.data();if(x.cashierId!==currentProfile.uid||x.status==='cancelled')return;count++;if(x.paymentMethod==='Tunai')cash+=+x.total||0;else non+=+x.total||0});const expected=(+openShift.openingCash||0)+cash;const c=openModal(`<h3>Tutup Shift</h3><div class="summary"><div class="summary-row"><span>Modal awal</span><b>${money(openShift.openingCash)}</b></div><div class="summary-row"><span>Penjualan tunai</span><b>${money(cash)}</b></div><div class="summary-row"><span>Non-tunai</span><b>${money(non)}</b></div><div class="summary-row"><span>Uang seharusnya</span><b>${money(expected)}</b></div><div class="summary-row"><span>Jumlah transaksi</span><b>${count}</b></div></div><form id="closeShiftForm" style="margin-top:14px"><label class="field">Uang aktual di kas<input name="actual" type="number" min="0" required value="${expected}"></label><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Batal</button><button class="btn btn-danger">Tutup Shift</button></div></form>`,{size:'modal-sm'});c.querySelector('#closeShiftForm').onsubmit=async e=>{e.preventDefault();const actual=num(new FormData(e.currentTarget).get('actual'));await updateDoc(doc(db,'shifts',openShift.id),{status:'closed',cashSales:cash,nonCashSales:non,expectedCash:expected,actualCash:actual,difference:actual-expected,transactionCount:count,closedAt:serverTimestamp()});await audit('tutup shift',`Selisih ${actual-expected}`);toast('Shift ditutup');closeModal();load()}}
