import { db } from './firebase-config.js';
import { collection, getDocs, doc, updateDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { $, $$, toast, openModal, closeModal, setPageTitle, escapeHtml, emptyState } from './utils.js';
import { currentProfile } from './auth.js';
import { audit } from './data.js';
let rows=[];
export async function renderUsers(container){setPageTitle('Pengguna');container.innerHTML=`<div class="page-head"><div><h3>Manajemen Pengguna</h3><p class="muted">Role disimpan di Firestore. Password tetap hanya dikelola Firebase Authentication.</p></div><button id="userHelp" class="btn btn-primary"><i class="fa-solid fa-user-plus"></i> Cara Tambah Akun</button></div><div id="userTable" class="card">Memuat...</div>`;$('#userHelp').onclick=()=>openModal(`<h3>Tambah akun kasir/admin</h3><ol><li>Buka Firebase Console → Authentication → Users.</li><li>Klik Add user, isi email dan password.</li><li>Salin UID user.</li><li>Buka Firestore → collection <code>users</code>.</li><li>Buat document ID sama persis dengan UID, lalu isi <code>name</code>, <code>email</code>, <code>role</code> (admin/kasir), <code>active</code> (true).</li></ol><p class="muted">Aplikasi sengaja tidak menyediakan pendaftaran admin publik.</p>`,{size:'modal-sm'});await load()}
async function load(){const s=await getDocs(collection(db,'users'));rows=s.docs.map(d=>({id:d.id,...d.data()}));$('#userTable').innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${escapeHtml(r.name||'-')}</b></td><td>${escapeHtml(r.email||'-')}</td><td>${escapeHtml(r.role||'-')}</td><td><span class="badge ${r.active===false?'danger':'success'}">${r.active===false?'Nonaktif':'Aktif'}</span></td><td><button class="btn btn-sm btn-ghost" data-edit="${r.id}" ${r.id===currentProfile.uid?'disabled':''}>Kelola</button></td></tr>`).join('')}</tbody></table></div>`:emptyState('Belum ada pengguna','Buat user di Firebase Authentication lalu dokumen users/{uid}.');$$('[data-edit]').forEach(b=>b.onclick=()=>form(rows.find(r=>r.id===b.dataset.edit)))}
function form(r){const c=openModal(`<h3>Kelola Pengguna</h3><form id="userForm"><label class="field">Nama<input name="name" required value="${escapeHtml(r.name||'')}"></label><label class="field" style="margin-top:10px">Role<select name="role"><option value="kasir" ${r.role==='kasir'?'selected':''}>Kasir</option><option value="admin" ${r.role==='admin'?'selected':''}>Admin</option></select></label><label class="field" style="margin-top:10px">Status<select name="active"><option value="true" ${r.active!==false?'selected':''}>Aktif</option><option value="false" ${r.active===false?'selected':''}>Nonaktif</option></select></label><div class="modal-actions"><button type="button" class="btn btn-ghost" data-close-modal>Batal</button><button class="btn btn-primary">Simpan</button></div></form>`,{size:'modal-sm'});c.querySelector('#userForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={name:String(fd.get('name')).trim(),role:fd.get('role'),active:fd.get('active')==='true',updatedAt:serverTimestamp()};await updateDoc(doc(db,'users',r.id),data);await audit('ubah pengguna',`${r.email}: ${data.role}/${data.active}`);toast('Pengguna diperbarui');closeModal();load()}}
